apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "dev-box.name" . }}-settings
  labels:
    {{- include "dev-box.labels" . | nindent 4 }}
data:
  settings.json: |
    {{- .Files.Get "files/settings.json" | nindent 4 }}
