{{- if not .Values.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "dev-box.name" . }}
  labels:
    {{- include "dev-box.labels" . | nindent 4 }}
type: Opaque
stringData:
  password: {{ .Values.password | quote }}
{{- end }}
